my_stocks = ["BEL.NS","DLF.NS","JIOFIN.NS","JMFINANCIL.NS","LTFOODS.NS","PARADEEP.NS","RPOWER.NS",
             "SAMHI.NS","ZEEL.NS"]

SHORT_TERM_STOCKS = ["BAJAJINDEF.NS","SCI.NS","NRAIL.NS","JUBLINGREA.NS","GUJAPOLLO.NS","DBREALTY.NS","MANCREDIT.NS","OSWALAGRO.NS",
                     "NAZARA.NS","GOODLUCK.NS","INDOTHAI.NS","KERNEX.NS","DELPHIFX.NS","KDDL.NS","SUBROS.NS"]

PENNY_STOCKS = ["TCIFINANCE.NS","ARTNIRMAN.NS","SHAH.NS","ROML.NS","CALSOFT.NS","SANCO.NS","TARAPUR.NS","OILCOUNTUB.NS","CYBERMEDIA.NS"]