my_stocks = []

SHORT_TERM_STOCKS = ["BAJAJINDEF.NS","SCI.NS","NRAIL.NS","JUBLINGREA.NS","GUJAPOLLO.NS","DBREALTY.NS","MANCREDIT.NS","OSWALAGRO.NS",
                     "NAZARA.NS","GOODLUCK.NS","INDOTHAI.NS","KERNEX.NS","DELPHIFX.NS","KDDL.NS","SUBROS.NS","GILLANDERS.NS",
                     "FCL .NS","JBCHEPHARM.NS","AFFORDABLE.NS",'ASHAPURMIN.NS',"ENDURANCE,NS","KFINTECH.NS","JPOLYINVST.NS",
                     "MEGASTAR.NS","QPOWER.NS","TOUCHWOOD.NS","TIIL.NS","BEML.NS","GALLANTT.NS"]

PENNY_STOCKS = ["TCIFINANCE.NS","ARTNIRMAN.NS","SHAH.NS","ROML.NS","CALSOFT.NS","SANCO.NS","TARAPUR.NS","OILCOUNTUB.NS","CYBERMEDIA.NS",
                "AAKASH.NS","JAIPURKURT.NS","CINEVISTA.NS","RTNPOWER.NS"]

NEW_STOCKS = ["SJS.NS","JUBLINGREA.NS","ASKAUTOLTD.NS","MEDIASSIST.NS","AKUMS.NS","CEIGALL.NS","AZAD.NS","ARVSMART.NS","SUBROS.NS",
              "LUMAXTECH.NS","RUSTOMJEE.NS","CAPACITE.NS","EPACK.NS","UDS.NS","ARTEMISMED.NS","ENTERO.NS","JINDALSAW.NS","WABAG.NS",
              "DODLA.NS","ROLEXRINGS.NS","HITECH.NS","PARKHOTELS.NS","TANLA.NS","JWL.NS","MARKSANS.NS","NITINSPIN.NS","STAR.NS","WEALTH.NS",
              "IFBIND.NS","SURAKSHA.NS","NETWEB.NS","SWSSOLAR.NS","INOXINDIA.NS","ENGINERSIN.NS","INNOVACAP.NS","MIDHANI.NS","AJAXENGG.NS",
              "SWARAJENG.NS","CAPITALSFB.NS","TIPSMUSIC.NS","TECHNOE.NS","PARADEEP.NS","ICRA.NS","PRICOLLTD.NS","EASEMYTRIP.NS","SUPRIYA.NS",
              "TEXRAIL.NS","AURIONPRO.NS","NAVNETEDUL.NS","J&KBANK.NS","EPIGRAL.NS","HPL.NS","INDRAMEDCO.NS","UNIECOM.NS","ZAGGLE.NS",
              "SURAJEST.NS","CARERATING.NS","GPTHEALTH.NS","TIMETECHNO.NS","DREAMFOLKS.NS","TRIDENT.NS","MHRIL.NS","GMDCLTD.NS","SCI.NS",
              "INDIANHUME.NS","RSYSTEMS.NS","LUXIND.NS","SANATHAN.NS","PNGJL.NS","ECOSMOBLTY.NS","GIPCL.NS","SHRIPISTON.NS","ANANDRATHI.NS",
              "MPSLTD.NS","AEROFLEX.NS","INGERRAND.NS","RAMCOIND.NS","ACE.NS","PGIL.NS","SURYAROSNI.NS","VAIBHAVGBL.NS","SILVERTUC.NS" ,
              "FOCE.NS","SPORTKING.NS","IPL.NS","JAICORPLTD.NS","JYOTISTRUC.NS","NDRAUTO.NS","VEEDOL.NS","DCW.NS","REMUS.NS","EIMCOELECO.NS",
              "GALAPREC.NS","QPOWER.NS","TAC.NS","IWEL.NS","BELRISE.NS","KRN.NS","TECHLABSE.NS","CREATIVE.NS","MARINE.NS","SERVOTECH.NS",
              "DEN.NS","RPTECH.NS","SMSPHARMA.NS","JGCHEM.NS","SIGACHI.NS","JSLL.NS","PASHUPATI.NS","RPTECH.NS","SRM.NS","VTM.NS","PRECWIRE.NS",
              "SOMICONVEY.NS","TARAPUR.NS","TIL.NS","VISHNU.NS","WELSPUNIND.NS","ZENTEC.NS","ZODIACLOTH.NS","ZEELEARN.NS","ZODIACLOTH.NS",] 

CASH_HEAVY = ["BAJFINANCE.NS","LT.NS","LTF.NS","PNBHOUSING.NS","RELIANCE.NS","SHRIRAMFIN.NS","TATACONSUM.NS","GPTINFRA.NS",
              "DLINKINDIA.NS","MPSLTD.NS","UNIONBANK.NS","GESHIP.NS","CANBK.NS","GMDCLTD.NS","RECLTD.NS","INDIANB.NS","GULFOILLUB.NS",
              "BEL.NS","DLF.NS","JIOFIN.NS","JMFINANCIL.NS","LTFOODS.NS","RPOWER.NS","SAMHI.NS"] 